#ifndef SHAREDWINDOWINFO_H
#define SHAREDWINDOWINFO_H

#include <QWidget>
#include <QMap>
#include <QVariant>
#include <QMessageBox>
#include <QStackedWidget>
#include <QPushButton>
#include <QVBoxLayout>
#include <QLabel>
#include <QComboBox>
#include <QCheckBox>
#include <QSpinBox>
#include <QJsonObject>
#include <QJsonDocument>
#include <QJsonArray>
#include <QGroupBox>
#include <QStringListModel>
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QTabBar>
#include <QLineEdit>
#include <QScrollArea>
#include <QFormLayout>
#include <QCompleter>
#include <QFileDialog>

class SharedCalculatorWindow{
protected:

public:
    QMap<QString, QStringList> nationalDexPokemonNamesAndForms = {
        {"Bulbasaur", {"—"}},
        {"Ivysaur", {"—"}},
        {"Venusaur", {"—"}},
        {"Charmander", {"—"}},
        {"Charmeleon", {"—"}},
        {"Charizard", {"—"}},
        {"Squirtle", {"—"}},
        {"Wartortle", {"—"}},
        {"Blastoise", {"—"}},
        {"Ekans", {"—"}},
        {"Arbok", {"—"}},
        {"Pikachu", {"Normal","Original","Hoenn","Sinnoh","Unova","Kalos","Alola","Partner","World"}},
        {"Raichu", {"Normal","Alolan"}},
        {"Sandshrew", {"Normal","Alolan"}},
        {"Sandslash", {"Normal","Alolan"}},
        {"Clefairy", {"—"}},
        {"Clefable", {"—"}},
        {"Vulpix", {"Normal","Alolan"}},
        {"Ninetales", {"Normal","Alolan"}},
        {"Jigglypuff", {"—"}},
        {"Wigglytuff", {"—"}},
        {"Oddish", {"—"}},
        {"Gloom", {"—"}},
        {"Vileplume", {"—"}},
        {"Venonat", {"—"}},
        {"Venomoth", {"—"}},
        {"Diglett", {"Normal","Alolan"}},
        {"Dugtrio", {"Normal","Alolan"}},
        {"Meowth", {"Normal","Alolan","Galarian"}},
        {"Persian", {"Normal","Alolan"}},
        {"Psyduck", {"—"}},
        {"Golduck", {"—"}},
        {"Mankey", {"—"}},
        {"Primeape", {"—"}},
        {"Growlithe", {"Normal","Hisuian"}},
        {"Arcanine", {"Normal","Hisuian"}},
        {"Poliwag", {"—"}},
        {"Poliwhirl", {"—"}},
        {"Poliwrath", {"—"}},
        {"Bellsprout", {"—"}},
        {"Weepinbell", {"—"}},
        {"Victreebel", {"—"}},
        {"Tentacool", {"—"}},
        {"Tentacruel", {"—"}},
        {"Geodude", {"Normal","Alolan"}},
        {"Graveler", {"Normal","Alolan"}},
        {"Golem", {"Normal","Alolan"}},
        {"Slowpoke", {"Normal","Galarian"}},
        {"Slowbro", {"Normal","Galarian"}},
        {"Magnemite", {"—"}},
        {"Magneton", {"—"}},
        {"Doduo", {"—"}},
        {"Dodrio", {"—"}},
        {"Seel", {"—"}},
        {"Dewgong", {"—"}},
        {"Grimer", {"Normal","Alolan"}},
        {"Muk", {"Normal","Alolan"}},
        {"Shellder", {"—"}},
        {"Cloyster", {"—"}},
        {"Gastly", {"—"}},
        {"Haunter", {"—"}},
        {"Gengar", {"—"}},
        {"Drowzee", {"—"}},
        {"Hypno", {"—"}},
        {"Voltorb", {"Normal","Hisuian"}},
        {"Electrode", {"Normal","Hisuian"}},
        {"Exeggcute", {"—"}},
        {"Exeggutor", {"Normal","Alolan"}},
        {"Hitmonlee", {"—"}},
        {"Hitmonchan", {"—"}},
        {"Koffing", {"—"}},
        {"Weezing", {"Normal","Galarian"}},
        {"Rhyhorn", {"—"}},
        {"Rhydon", {"—"}},
        {"Chansey", {"—"}},
        {"Horsea", {"—"}},
        {"Seadra", {"—"}},
        {"Scyther", {"—"}},
        {"Electabuzz", {"—"}},
        {"Magmar", {"—"}},
        {"Tauros", {"Normal","Paldean (Combat)","Paldean (Blaze)","Paldean (Aqua)"}},
        {"Magikarp", {"—"}},
        {"Gyarados", {"—"}},
        {"Lapras", {"—"}},
        {"Ditto", {"—"}},
        {"Eevee", {"—"}},
        {"Vaporeon", {"—"}},
        {"Jolteon", {"—"}},
        {"Flareon", {"—"}},
        {"Porygon", {"—"}},
        {"Snorlax", {"—"}},
        {"Articuno", {"Normal","Galarian"}},
        {"Zapdos", {"Normal","Galarian"}},
        {"Moltres", {"Normal","Galarian"}},
        {"Dratini", {"—"}},
        {"Dragonair", {"—"}},
        {"Dragonite", {"—"}},
        {"Mewtwo", {"—"}},
        {"Mew", {"—"}},
        {"Chikorita", {"—"}},
        {"Bayleef", {"—"}},
        {"Meganium", {"—"}},
        {"Cyndaquil", {"—"}},
        {"Quilava", {"—"}},
        {"Typhlosion", {"Normal","Hisuian"}},
        {"Totodile", {"—"}},
        {"Croconaw", {"—"}},
        {"Feraligatr", {"—"}},
        {"Sentret", {"—"}},
        {"Furret", {"—"}},
        {"Hoothoot", {"—"}},
        {"Noctowl", {"—"}},
        {"Spinarak", {"—"}},
        {"Ariados", {"—"}},
        {"Chinchou", {"—"}},
        {"Lanturn", {"—"}},
        {"Pichu", {"—"}},
        {"Cleffa", {"—"}},
        {"Igglybuff", {"—"}},
        {"Mareep", {"—"}},
        {"Flaaffy", {"—"}},
        {"Ampharos", {"—"}},
        {"Bellossom", {"—"}},
        {"Marill", {"—"}},
        {"Azumarill", {"—"}},
        {"Sudowoodo", {"—"}},
        {"Politoed", {"—"}},
        {"Hoppip", {"—"}},
        {"Skiploom", {"—"}},
        {"Jumpluff", {"—"}},
        {"Aipom", {"—"}},
        {"Sunkern", {"—"}},
        {"Sunflora", {"—"}},
        {"Yanma", {"—"}},
        {"Wooper", {"Normal","Paldean"}},
        {"Quagsire", {"—"}},
        {"Espeon", {"—"}},
        {"Umbreon", {"—"}},
        {"Murkrow", {"—"}},
        {"Slowking", {"Normal","Galarian"}},
        {"Misdreavus", {"—"}},
        {"Girafarig", {"—"}},
        {"Pineco", {"—"}},
        {"Forretress", {"—"}},
        {"Dunsparce", {"—"}},
        {"Gligar", {"—"}},
        {"Snubbull", {"—"}},
        {"Granbull", {"—"}},
        {"Qwilfish", {"Normal","Hisuian"}},
        {"Scizor", {"—"}},
        {"Heracross", {"—"}},
        {"Sneasel", {"Normal","Hisuian"}},
        {"Teddiursa", {"—"}},
        {"Ursaring", {"—"}},
        {"Slugma", {"—"}},
        {"Magcargo", {"—"}},
        {"Swinub", {"—"}},
        {"Piloswine", {"—"}},
        {"Delibird", {"—"}},
        {"Skarmory", {"—"}},
        {"Houndour", {"—"}},
        {"Houndoom", {"—"}},
        {"Kingdra", {"—"}},
        {"Phanpy", {"—"}},
        {"Donphan", {"—"}},
        {"Porygon2", {"—"}},
        {"Stantler", {"—"}},
        {"Smeargle", {"—"}},
        {"Tyrogue", {"—"}},
        {"Hitmontop", {"—"}},
        {"Elekid", {"—"}},
        {"Magby", {"—"}},
        {"Blissey", {"—"}},
        {"Raikou", {"—"}},
        {"Entei", {"—"}},
        {"Suicune", {"—"}},
        {"Larvitar", {"—"}},
        {"Pupitar", {"—"}},
        {"Tyranitar", {"—"}},
        {"Lugia", {"—"}},
        {"Ho-Oh", {"—"}},
        {"Treecko", {"—"}},
        {"Grovyle", {"—"}},
        {"Sceptile", {"—"}},
        {"Torchic", {"—"}},
        {"Combusken", {"—"}},
        {"Blaziken", {"—"}},
        {"Mudkip", {"—"}},
        {"Marshtomp", {"—"}},
        {"Swampert", {"—"}},
        {"Poochyena", {"—"}},
        {"Mightyena", {"—"}},
        {"Lotad", {"—"}},
        {"Lombre", {"—"}},
        {"Ludicolo", {"—"}},
        {"Seedot", {"—"}},
        {"Nuzleaf", {"—"}},
        {"Shiftry", {"—"}},
        {"Wingull", {"—"}},
        {"Pelipper", {"—"}},
        {"Ralts", {"—"}},
        {"Kirlia", {"—"}},
        {"Gardevoir", {"—"}},
        {"Surskit", {"—"}},
        {"Masquerain", {"—"}},
        {"Shroomish", {"—"}},
        {"Breloom", {"—"}},
        {"Slakoth", {"—"}},
        {"Vigoroth", {"—"}},
        {"Slaking", {"—"}},
        {"Makuhita", {"—"}},
        {"Hariyama", {"—"}},
        {"Azurill", {"—"}},
        {"Nosepass", {"—"}},
        {"Sableye", {"—"}},
        {"Meditite", {"—"}},
        {"Medicham", {"—"}},
        {"Plusle", {"—"}},
        {"Minun", {"—"}},
        {"Volbeat", {"—"}},
        {"Illumise", {"—"}},
        {"Gulpin", {"—"}},
        {"Swalot", {"—"}},
        {"Numel", {"—"}},
        {"Camerupt", {"—"}},
        {"Torkoal", {"—"}},
        {"Spoink", {"—"}},
        {"Grumpig", {"—"}},
        {"Trapinch", {"—"}},
        {"Vibrava", {"—"}},
        {"Flygon", {"—"}},
        {"Cacnea", {"—"}},
        {"Cacturne", {"—"}},
        {"Swablu", {"—"}},
        {"Altaria", {"—"}},
        {"Zangoose", {"—"}},
        {"Seviper", {"—"}},
        {"Barboach", {"—"}},
        {"Whiscash", {"—"}},
        {"Corphish", {"—"}},
        {"Crawdaunt", {"—"}},
        {"Feebas", {"—"}},
        {"Milotic", {"—"}},
        {"Shuppet", {"—"}},
        {"Banette", {"—"}},
        {"Duskull", {"—"}},
        {"Dusclops", {"—"}},
        {"Tropius", {"—"}},
        {"Chimecho", {"—"}},
        {"Snorunt", {"—"}},
        {"Glalie", {"—"}},
        {"Luvdisc", {"—"}},
        {"Bagon", {"—"}},
        {"Shelgon", {"—"}},
        {"Salamence", {"—"}},
        {"Beldum", {"—"}},
        {"Metang", {"—"}},
        {"Metagross", {"—"}},
        {"Regirock", {"—"}},
        {"Regice", {"—"}},
        {"Registeel", {"—"}},
        {"Latias", {"—"}},
        {"Latios", {"—"}},
        {"Kyogre", {"—"}},
        {"Groudon", {"—"}},
        {"Rayquaza", {"—"}},
        {"Jirachi", {"—"}},
        {"Deoxys", {"Normal","Attack","Defense","Speed"}},
        {"Turtwig", {"—"}},
        {"Grotle", {"—"}},
        {"Torterra", {"—"}},
        {"Chimchar", {"—"}},
        {"Monferno", {"—"}},
        {"Infernape", {"—"}},
        {"Piplup", {"—"}},
        {"Prinplup", {"—"}},
        {"Empoleon", {"—"}},
        {"Starly", {"—"}},
        {"Staravia", {"—"}},
        {"Staraptor", {"—"}},
        {"Kricketot", {"—"}},
        {"Kricketune", {"—"}},
        {"Shinx", {"—"}},
        {"Luxio", {"—"}},
        {"Luxray", {"—"}},
        {"Cranidos", {"—"}},
        {"Rampardos", {"—"}},
        {"Shieldon", {"—"}},
        {"Bastiodon", {"—"}},
        {"Combee", {"—"}},
        {"Vespiquen", {"—"}},
        {"Pachirisu", {"—"}},
        {"Buizel", {"—"}},
        {"Floatzel", {"—"}},
        {"Shellos", {"West","East"}},
        {"Gastrodon", {"West","East"}},
        {"Ambipom", {"—"}},
        {"Drifloon", {"—"}},
        {"Drifblim", {"—"}},
        {"Mismagius", {"—"}},
        {"Honchkrow", {"—"}},
        {"Chingling", {"—"}},
        {"Stunky", {"—"}},
        {"Skuntank", {"—"}},
        {"Bronzor", {"—"}},
        {"Bronzong", {"—"}},
        {"Bonsly", {"—"}},
        {"Happiny", {"—"}},
        {"Spiritomb", {"—"}},
        {"Gible", {"—"}},
        {"Gabite", {"—"}},
        {"Garchomp", {"—"}},
        {"Munchlax", {"—"}},
        {"Riolu", {"—"}},
        {"Lucario", {"—"}},
        {"Hippopotas", {"—"}},
        {"Hippowdon", {"—"}},
        {"Croagunk", {"—"}},
        {"Toxicroak", {"—"}},
        {"Finneon", {"—"}},
        {"Lumineon", {"—"}},
        {"Snover", {"—"}},
        {"Abomasnow", {"—"}},
        {"Weavile", {"—"}},
        {"Magnezone", {"—"}},
        {"Rhyperior", {"—"}},
        {"Electivire", {"—"}},
        {"Magmortar", {"—"}},
        {"Yanmega", {"—"}},
        {"Leafeon", {"—"}},
        {"Glaceon", {"—"}},
        {"Gliscor", {"—"}},
        {"Mamoswine", {"—"}},
        {"Porygon-Z", {"—"}},
        {"Gallade", {"—"}},
        {"Probopass", {"—"}},
        {"Dusknoir", {"—"}},
        {"Froslass", {"—"}},
        {"Rotom", {"Normal","Heat","Wash","Frost","Fan","Mow"}},
        {"Uxie", {"—"}},
        {"Mesprit", {"—"}},
        {"Azelf", {"—"}},
        {"Dialga", {"Normal","Origin"}},
        {"Palkia", {"Normal","Origin"}},
        {"Heatran", {"—"}},
        {"Regigigas", {"—"}},
        {"Giratina", {"Altered","Origin"}},
        {"Cresselia", {"—"}},
        {"Phione", {"—"}},
        {"Manaphy", {"—"}},
        {"Darkrai", {"—"}},
        {"Shaymin", {"Land","Sky"}},
        {"Arceus", {"Normal","Fighting","Flying","Poison","Ground","Rock","Bug","Ghost","Steel","Fire","Water","Grass","Electric","Psychic","Ice","Dragon","Dark","Fairy"}},
        {"Snivy", {"—"}},
        {"Servine", {"—"}},
        {"Serperior", {"—"}},
        {"Tepig", {"—"}},
        {"Pignite", {"—"}},
        {"Emboar", {"—"}},
        {"Oshawott", {"—"}},
        {"Dewott", {"—"}},
        {"Samurott", {"Normal","Hisuian"}},
        {"Blitzle", {"—"}},
        {"Zebstrika", {"—"}},
        {"Drilbur", {"—"}},
        {"Excadrill", {"—"}},
        {"Timburr", {"—"}},
        {"Gurdurr", {"—"}},
        {"Conkeldurr", {"—"}},
        {"Sewaddle", {"—"}},
        {"Swadloon", {"—"}},
        {"Leavanny", {"—"}},
        {"Cottonee", {"—"}},
        {"Whimsicott", {"—"}},
        {"Petilil", {"—"}},
        {"Lilligant", {"Normal","Hisuian"}},
        {"Basculin", {"Red","Blue","White"}},
        {"Sandile", {"—"}},
        {"Krokorok", {"—"}},
        {"Krookodile", {"—"}},
        {"Scraggy", {"—"}},
        {"Scrafty", {"—"}},
        {"Zorua", {"Normal","Hisuian"}},
        {"Zoroark", {"Normal","Hisuian"}},
        {"Minccino", {"—"}},
        {"Cinccino", {"—"}},
        {"Gothita", {"—"}},
        {"Gothorita", {"—"}},
        {"Gothitelle", {"—"}},
        {"Solosis", {"—"}},
        {"Duosion", {"—"}},
        {"Reuniclus", {"—"}},
        {"Ducklett", {"—"}},
        {"Swanna", {"—"}},
        {"Deerling", {"Spring","Summer","Autumn","Winter"}},
        {"Sawsbuck", {"Spring","Summer","Autumn","Winter"}},
        {"Foongus", {"—"}},
        {"Amoonguss", {"—"}},
        {"Alomomola", {"—"}},
        {"Joltik", {"—"}},
        {"Galvantula", {"—"}},
        {"Tynamo", {"—"}},
        {"Eelektrik", {"—"}},
        {"Eelektross", {"—"}},
        {"Litwick", {"—"}},
        {"Lampent", {"—"}},
        {"Chandelure", {"—"}},
        {"Axew", {"—"}},
        {"Fraxure", {"—"}},
        {"Haxorus", {"—"}},
        {"Cubchoo", {"—"}},
        {"Beartic", {"—"}},
        {"Cryogonal", {"—"}},
        {"Mienfoo", {"—"}},
        {"Mienshao", {"—"}},
        {"Golett", {"—"}},
        {"Golurk", {"—"}},
        {"Pawniard", {"—"}},
        {"Bisharp", {"—"}},
        {"Rufflet", {"—"}},
        {"Braviary", {"Normal","Hisuian"}},
        {"Vullaby", {"—"}},
        {"Mandibuzz", {"—"}},
        {"Deino", {"—"}},
        {"Zweilous", {"—"}},
        {"Hydreigon", {"—"}},
        {"Larvesta", {"—"}},
        {"Volcarona", {"—"}},
        {"Cobalion", {"—"}},
        {"Terrakion", {"—"}},
        {"Virizion", {"—"}},
        {"Tornadus", {"Incarnate","Therian"}},
        {"Thundurus", {"Incarnate","Therian"}},
        {"Reshiram", {"—"}},
        {"Zekrom", {"—"}},
        {"Landorus", {"Incarnate","Therian"}},
        {"Kyurem", {"Normal","White","Black"}},
        {"Keldeo", {"Ordinary","Resolute"}},
        {"Meloetta", {"Aria","Pirouette"}},
        {"Chespin", {"—"}},
        {"Quilladin", {"—"}},
        {"Chesnaught", {"—"}},
        {"Fennekin", {"—"}},
        {"Braixen", {"—"}},
        {"Delphox", {"—"}},
        {"Froakie", {"—"}},
        {"Frogadier", {"—"}},
        {"Greninja", {"Normal","Battle Bond"}},
        {"Fletchling", {"—"}},
        {"Fletchinder", {"—"}},
        {"Talonflame", {"—"}},
        {"Scatterbug", {"Icy Snow","Polar","Tundra","Continental","Garden","Elegant","Meadow","Modern","Marine","Archipelago","High Plains","Sandstorm","River","Monsoon","Savanna","Sun","Ocean","Jungle","Fancy","Poké Ball"}},
        {"Spewpa", {"Icy Snow","Polar","Tundra","Continental","Garden","Elegant","Meadow","Modern","Marine","Archipelago","High Plains","Sandstorm","River","Monsoon","Savanna","Sun","Ocean","Jungle","Fancy","Poké Ball"}},
        {"Vivillon", {"Icy Snow","Polar","Tundra","Continental","Garden","Elegant","Meadow","Modern","Marine","Archipelago","High Plains","Sandstorm","River","Monsoon","Savanna","Sun","Ocean","Jungle","Fancy","Poké Ball"}},
        {"Litleo", {"—"}},
        {"Pyroar", {"—"}},
        {"Flabébé", {"Red","Yellow","Orange","Blue","White"}},
        {"Floette", {"Red","Yellow","Orange","Blue","White","Eternal"}},
        {"Florges", {"Red","Yellow","Orange","Blue","White"}},
        {"Skiddo", {"—"}},
        {"Gogoat", {"—"}},
        {"Espurr", {"—"}},
        {"Meowstic", {"Male","Female"}},
        {"Inkay", {"—"}},
        {"Malamar", {"—"}},
        {"Skrelp", {"—"}},
        {"Dragalge", {"—"}},
        {"Clauncher", {"—"}},
        {"Clawitzer", {"—"}},
        {"Sylveon", {"—"}},
        {"Hawlucha", {"—"}},
        {"Dedenne", {"—"}},
        {"Carbink", {"—"}},
        {"Goomy", {"—"}},
        {"Sliggoo", {"Normal","Hisuian"}},
        {"Goodra", {"Normal","Hisuian"}},
        {"Klefki", {"—"}},
        {"Phantump", {"—"}},
        {"Trevenant", {"—"}},
        {"Bergmite", {"—"}},
        {"Avalugg", {"Normal","Hisuian"}},
        {"Noibat", {"—"}},
        {"Noivern", {"—"}},
        {"Diancie", {"—"}},
        {"Hoopa", {"Confined","Unbound"}},
        {"Volcanion", {"—"}},
        {"Rowlet", {"—"}},
        {"Dartrix", {"—"}},
        {"Decidueye", {"Normal","Hisuian"}},
        {"Litten", {"—"}},
        {"Torracat", {"—"}},
        {"Incineroar", {"—"}},
        {"Popplio", {"—"}},
        {"Brionne", {"—"}},
        {"Primarina", {"—"}},
        {"Pikipek", {"—"}},
        {"Trumbeak", {"—"}},
        {"Toucannon", {"—"}},
        {"Yungoos", {"—"}},
        {"Gumshoos", {"—"}},
        {"Grubbin", {"—"}},
        {"Charjabug", {"—"}},
        {"Vikavolt", {"—"}},
        {"Crabrawler", {"—"}},
        {"Crabominable", {"—"}},
        {"Oricorio", {"Baile","Pom-Pom","Pa’u","Sensu"}},
        {"Cutiefly", {"—"}},
        {"Ribombee", {"—"}},
        {"Rockruff", {"Normal","Own Tempo"}},
        {"Lycanroc", {"Midday","Midnight","Dusk"}},
        {"Mareanie", {"—"}},
        {"Toxapex", {"—"}},
        {"Mudbray", {"—"}},
        {"Mudsdale", {"—"}},
        {"Dewpider", {"—"}},
        {"Araquanid", {"—"}},
        {"Fomantis", {"—"}},
        {"Lurantis", {"—"}},
        {"Salandit", {"—"}},
        {"Salazzle", {"—"}},
        {"Bounsweet", {"—"}},
        {"Steenee", {"—"}},
        {"Tsareena", {"—"}},
        {"Comfey", {"—"}},
        {"Oranguru", {"—"}},
        {"Passimian", {"—"}},
        {"Sandygast", {"—"}},
        {"Palossand", {"—"}},
        {"Minior", {"M-Red","M-Orange","M-Yellow","M-Green","M-Blue","M-Indigo","M-Violet","C-Red","C-Orange","C-Yellow","C-Green","C-Blue","C-Indigo","C-Violet"}},
        {"Komala", {"—"}},
        {"Mimikyu", {"Disguised","Busted"}},
        {"Bruxish", {"—"}},
        {"Jangmo-o", {"—"}},
        {"Hakamo-o", {"—"}},
        {"Kommo-o", {"—"}},
        {"Cosmog", {"—"}},
        {"Cosmoem", {"—"}},
        {"Solgaleo", {"—"}},
        {"Lunala", {"—"}},
        {"Necrozma", {"Normal","Dusk Mane","Dawn Wings"}},
        {"Magearna", {"Normal","Original"}},
        {"Grookey", {"—"}},
        {"Thwackey", {"—"}},
        {"Rillaboom", {"—"}},
        {"Scorbunny", {"—"}},
        {"Raboot", {"—"}},
        {"Cinderace", {"—"}},
        {"Sobble", {"—"}},
        {"Drizzile", {"—"}},
        {"Inteleon", {"—"}},
        {"Skwovet", {"—"}},
        {"Greedent", {"—"}},
        {"Rookidee", {"—"}},
        {"Corvisquire", {"—"}},
        {"Corviknight", {"—"}},
        {"Chewtle", {"—"}},
        {"Drednaw", {"—"}},
        {"Rolycoly", {"—"}},
        {"Carkol", {"—"}},
        {"Coalossal", {"—"}},
        {"Applin", {"—"}},
        {"Flapple", {"—"}},
        {"Appletun", {"—"}},
        {"Silicobra", {"—"}},
        {"Sandaconda", {"—"}},
        {"Cramorant", {"Normal","Gulping","Gorging"}},
        {"Arrokuda", {"—"}},
        {"Barraskewda", {"—"}},
        {"Toxel", {"—"}},
        {"Toxtricity", {"Amped","Low Key"}},
        {"Sinistea", {"Phony","Antique"}},
        {"Polteageist", {"Phony","Antique"}},
        {"Hatenna", {"—"}},
        {"Hattrem", {"—"}},
        {"Hatterene", {"—"}},
        {"Impidimp", {"—"}},
        {"Morgrem", {"—"}},
        {"Grimmsnarl", {"—"}},
        {"Perrserker", {"—"}},
        {"Milcery", {"—"}},
        {"Alcremie", {"Vanilla Cream","Ruby Cream","Matcha Cream","Mint Cream","Lemon Cream","Salted Cream","Ruby Swirl","Caramel Swirl","Rainbow Swirl"}},
        {"Falinks", {"—"}},
        {"Pincurchin", {"—"}},
        {"Snom", {"—"}},
        {"Frosmoth", {"—"}},
        {"Stonjourner", {"—"}},
        {"Eiscue", {"Ice Face","Noice Face"}},
        {"Indeedee", {"Male","Female"}},
        {"Morpeko", {"Full Belly","Hangry"}},
        {"Cufant", {"—"}},
        {"Copperajah", {"—"}},
        {"Duraludon", {"—"}},
        {"Dreepy", {"—"}},
        {"Drakloak", {"—"}},
        {"Dragapult", {"—"}},
        {"Zacian", {"Hero","Crowned"}},
        {"Zamazenta", {"Hero","Crowned"}},
        {"Eternatus", {"—"}},
        {"Kubfu", {"—"}},
        {"Urshifu", {"Single","Rapid"}},
        {"Zarude", {"Normal","Dada"}},
        {"Regieleki", {"—"}},
        {"Regidrago", {"—"}},
        {"Glastrier", {"—"}},
        {"Spectrier", {"—"}},
        {"Calyrex", {"Normal","Ice","Shadow"}},
        {"Wyrdeer", {"—"}},
        {"Kleavor", {"—"}},
        {"Ursaluna", {"Normal","Bloodmoon"}},
        {"Basculegion", {"Male","Female"}},
        {"Sneasler", {"—"}},
        {"Overqwil", {"—"}},
        {"Enamorus", {"Incarnate","Therian"}},
        {"Sprigatito", {"—"}},
        {"Floragato", {"—"}},
        {"Meowscarada", {"—"}},
        {"Fuecoco", {"—"}},
        {"Crocalor", {"—"}},
        {"Skeledirge", {"—"}},
        {"Quaxly", {"—"}},
        {"Quaxwell", {"—"}},
        {"Quaquaval", {"—"}},
        {"Lechonk", {"—"}},
        {"Oinkologne", {"Male","Female"}},
        {"Tarountula", {"—"}},
        {"Spidops", {"—"}},
        {"Nymble", {"—"}},
        {"Lokix", {"—"}},
        {"Pawmi", {"—"}},
        {"Pawmo", {"—"}},
        {"Pawmot", {"—"}},
        {"Tandemaus", {"—"}},
        {"Maushold", {"Three","Four"}},
        {"Fidough", {"—"}},
        {"Dachsbun", {"—"}},
        {"Smoliv", {"—"}},
        {"Dolliv", {"—"}},
        {"Arboliva", {"—"}},
        {"Squawkabilly", {"Green","Blue","Yellow","White"}},
        {"Nacli", {"—"}},
        {"Naclstack", {"—"}},
        {"Garganacl", {"—"}},
        {"Charcadet", {"—"}},
        {"Armarouge", {"—"}},
        {"Ceruledge", {"—"}},
        {"Tadbulb", {"—"}},
        {"Bellibolt", {"—"}},
        {"Wattrel", {"—"}},
        {"Kilowattrel", {"—"}},
        {"Maschiff", {"—"}},
        {"Mabosstiff", {"—"}},
        {"Shroodle", {"—"}},
        {"Grafaiai", {"—"}},
        {"Bramblin", {"—"}},
        {"Brambleghast", {"—"}},
        {"Toedscool", {"—"}},
        {"Toedscruel", {"—"}},
        {"Klawf", {"—"}},
        {"Capsakid", {"—"}},
        {"Scovillain", {"—"}},
        {"Rellor", {"—"}},
        {"Rabsca", {"—"}},
        {"Flittle", {"—"}},
        {"Espathra", {"—"}},
        {"Tinkatink", {"—"}},
        {"Tinkatuff", {"—"}},
        {"Tinkaton", {"—"}},
        {"Wiglett", {"—"}},
        {"Wugtrio", {"—"}},
        {"Bombirdier", {"—"}},
        {"Finizen", {"—"}},
        {"Palafin", {"Zero","Hero"}},
        {"Varoom", {"—"}},
        {"Revavroom", {"—"}},
        {"Cyclizar", {"—"}},
        {"Orthworm", {"—"}},
        {"Glimmet", {"—"}},
        {"Glimmora", {"—"}},
        {"Greavard", {"—"}},
        {"Houndstone", {"—"}},
        {"Flamigo", {"—"}},
        {"Cetoddle", {"—"}},
        {"Cetitan", {"—"}},
        {"Veluza", {"—"}},
        {"Dondozo", {"—"}},
        {"Tatsugiri", {"Curly","Droopy","Stretchy"}},
        {"Annihilape", {"—"}},
        {"Clodsire", {"—"}},
        {"Farigiraf", {"—"}},
        {"Dudunsparce", {"Two","Three"}},
        {"Kingambit", {"—"}},
        {"Great Tusk", {"—"}},
        {"Scream Tail", {"—"}},
        {"Brute Bonnet", {"—"}},
        {"Flutter Mane", {"—"}},
        {"Slither Wing", {"—"}},
        {"Sandy Shocks", {"—"}},
        {"Iron Treads", {"—"}},
        {"Iron Bundle", {"—"}},
        {"Iron Hands", {"—"}},
        {"Iron Jugulis", {"—"}},
        {"Iron Moth", {"—"}},
        {"Iron Thorns", {"—"}},
        {"Frigibax", {"—"}},
        {"Arctibax", {"—"}},
        {"Baxcalibur", {"—"}},
        {"Gimmighoul", {"Chest","Roaming"}},
        {"Gholdengo", {"—"}},
        {"Wo-Chien", {"—"}},
        {"Chien-Pao", {"—"}},
        {"Ting-Lu", {"—"}},
        {"Chi-Yu", {"—"}},
        {"Roaring Moon", {"—"}},
        {"Iron Valiant", {"—"}},
        {"Koraidon", {"Apex","Limited","Sprinting","Swimming","Gliding"}},
        {"Miraidon", {"Ultimate","Low-Power","Drive","Aquatic","Glide"}},
        {"Walking Wake", {"—"}},
        {"Iron Leaves", {"—"}},
        {"Dipplin", {"—"}},
        {"Poltchageist", {"Counterfeit","Artisan"}},
        {"Sinistcha", {"Unremarkable","Masterpiece"}},
        {"Okidogi", {"—"}},
        {"Munkidori", {"—"}},
        {"Fezandipiti", {"—"}},
        {"Ogerpon", {"Teal","Wellspring","Hearthflame","Cornerstone"}},
        {"Archaludon", {"—"}},
        {"Hydrapple", {"—"}},
        {"Gouging Fire", {"—"}},
        {"Raging Bolt", {"—"}},
        {"Iron Boulder", {"—"}},
        {"Iron Crown", {"—"}},
        {"Terapagos", {"Normal","Terastal","Stellar"}},
        {"Pecharunt", {"—"}},
    };

    QStringList moves = {
        "10,000,000 Volt Thunderbolt",
        "Absorb",
        "Accelerock",
        "Acid",
        "Acid Armor",
        "Acid Downpour",
        "Acid Spray",
        "Acrobatics",
        "Acupressure",
        "Aerial Ace",
        "Aeroblast",
        "After You",
        "Agility",
        "Air Cutter",
        "Air Slash",
        "All-Out Pummeling",
        "Alluring Voice",
        "Ally Switch",
        "Amnesia",
        "Anchor Shot",
        "Ancient Power",
        "Apple Acid",
        "Aqua Cutter",
        "Aqua Jet",
        "Aqua Ring",
        "Aqua Step",
        "Aqua Tail",
        "Arm Thrust",
        "Armor Cannon",
        "Aromatherapy",
        "Aromatic Mist",
        "Assist",
        "Assurance",
        "Astonish",
        "Astral Barrage",
        "Attack Order",
        "Attract",
        "Aura Sphere",
        "Aura Wheel",
        "Aurora Beam",
        "Aurora Veil",
        "Autotomize",
        "Avalanche",
        "Axe Kick",
        "Baby-Doll Eyes",
        "Baddy Bad",
        "Baneful Bunker",
        "Barb Barrage",
        "Barrage",
        "Barrier",
        "Baton Pass",
        "Beak Blast",
        "Beat Up",
        "Behemoth Bash",
        "Behemoth Blade",
        "Belch",
        "Belly Drum",
        "Bestow",
        "Bide",
        "Bind",
        "Bite",
        "Bitter Blade",
        "Bitter Malice",
        "Black Hole Eclipse",
        "Blast Burn",
        "Blaze Kick",
        "Blazing Torque",
        "Bleakwind Storm",
        "Blizzard",
        "Block",
        "Blood Moon",
        "Bloom Doom",
        "Blue Flare",
        "Body Press",
        "Body Slam",
        "Bolt Beak",
        "Bolt Strike",
        "Bone Club",
        "Bone Rush",
        "Bonemerang",
        "Boomburst",
        "Bounce",
        "Bouncy Bubble",
        "Branch Poke",
        "Brave Bird",
        "Breaking Swipe",
        "Breakneck Blitz",
        "Brick Break",
        "Brine",
        "Brutal Swing",
        "Bubble",
        "Bubble Beam",
        "Bug Bite",
        "Bug Buzz",
        "Bulk Up",
        "Bulldoze",
        "Bullet Punch",
        "Bullet Seed",
        "Burn Up",
        "Burning Bulwark",
        "Burning Jealousy",
        "Buzzy Buzz",
        "Calm Mind",
        "Camouflage",
        "Captivate",
        "Catastropika",
        "Ceaseless Edge",
        "Celebrate",
        "Charge",
        "Charge Beam",
        "Charm",
        "Chatter",
        "Chilling Water",
        "Chilly Reception",
        "Chip Away",
        "Chloroblast",
        "Circle Throw",
        "Clamp",
        "Clanging Scales",
        "Clangorous Soul",
        "Clangorous Soulblaze",
        "Clear Smog",
        "Close Combat",
        "Coaching",
        "Coil",
        "Collision Course",
        "Combat Torque",
        "Comet Punch",
        "Comeuppance",
        "Confide",
        "Confuse Ray",
        "Confusion",
        "Constrict",
        "Continental Crush",
        "Conversion",
        "Conversion 2",
        "Copycat",
        "Core Enforcer",
        "Corkscrew Crash",
        "Corrosive Gas",
        "Cosmic Power",
        "Cotton Guard",
        "Cotton Spore",
        "Counter",
        "Court Change",
        "Covet",
        "Crabhammer",
        "Crafty Shield",
        "Cross Chop",
        "Cross Poison",
        "Crunch",
        "Crush Claw",
        "Crush Grip",
        "Curse",
        "Cut",
        "Dark Pulse",
        "Dark Void",
        "Darkest Lariat",
        "Dazzling Gleam",
        "Decorate",
        "Defend Order",
        "Defense Curl",
        "Defog",
        "Destiny Bond",
        "Detect",
        "Devastating Drake",
        "Diamond Storm",
        "Dig",
        "Dire Claw",
        "Disable",
        "Disarming Voice",
        "Discharge",
        "Dive",
        "Dizzy Punch",
        "Doodle",
        "Doom Desire",
        "Double Hit",
        "Double Iron Bash",
        "Double Kick",
        "Double Shock",
        "Double Slap",
        "Double Team",
        "Double-Edge",
        "Draco Meteor",
        "Dragon Ascent",
        "Dragon Breath",
        "Dragon Cheer",
        "Dragon Claw",
        "Dragon Dance",
        "Dragon Darts",
        "Dragon Energy",
        "Dragon Hammer",
        "Dragon Pulse",
        "Dragon Rage",
        "Dragon Rush",
        "Dragon Tail",
        "Drain Punch",
        "Draining Kiss",
        "Dream Eater",
        "Drill Peck",
        "Drill Run",
        "Drum Beating",
        "Dual Chop",
        "Dual Wingbeat",
        "Dynamax Cannon",
        "Dynamic Punch",
        "Earth Power",
        "Earthquake",
        "Echoed Voice",
        "Eerie Impulse",
        "Eerie Spell",
        "Egg Bomb",
        "Electric Terrain",
        "Electrify",
        "Electro Ball",
        "Electro Drift",
        "Electro Shot",
        "Electroweb",
        "Embargo",
        "Ember",
        "Encore",
        "Endeavor",
        "Endure",
        "Energy Ball",
        "Entrainment",
        "Eruption",
        "Esper Wing",
        "Eternabeam",
        "Expanding Force",
        "Explosion",
        "Extrasensory",
        "Extreme Evoboost",
        "Extreme Speed",
        "Facade",
        "Fairy Lock",
        "Fairy Wind",
        "Fake Out",
        "Fake Tears",
        "False Surrender",
        "False Swipe",
        "Feather Dance",
        "Feint",
        "Feint Attack",
        "Fell Stinger",
        "Fickle Beam",
        "Fiery Dance",
        "Fiery Wrath",
        "Fillet Away",
        "Final Gambit",
        "Fire Blast",
        "Fire Fang",
        "Fire Lash",
        "Fire Pledge",
        "Fire Punch",
        "Fire Spin",
        "First Impression",
        "Fishious Rend",
        "Fissure",
        "Flail",
        "Flame Burst",
        "Flame Charge",
        "Flame Wheel",
        "Flamethrower",
        "Flare Blitz",
        "Flash",
        "Flash Cannon",
        "Flatter",
        "Fleur Cannon",
        "Fling",
        "Flip Turn",
        "Floaty Fall",
        "Floral Healing",
        "Flower Shield",
        "Flower Trick",
        "Fly",
        "Flying Press",
        "Focus Blast",
        "Focus Energy",
        "Focus Punch",
        "Follow Me",
        "Force Palm",
        "Foresight",
        "Forest's Curse",
        "Foul Play",
        "Freeze Shock",
        "Freeze-Dry",
        "Freezing Glare",
        "Freezy Frost",
        "Frenzy Plant",
        "Frost Breath",
        "Frustration",
        "Fury Attack",
        "Fury Cutter",
        "Fury Swipes",
        "Fusion Bolt",
        "Fusion Flare",
        "Future Sight",
        "G-Max Befuddle",
        "G-Max Cannonade",
        "G-Max Centiferno",
        "G-Max Chi Strike",
        "G-Max Cuddle",
        "G-Max Depletion",
        "G-Max Drum Solo",
        "G-Max Finale",
        "G-Max Fireball",
        "G-Max Foam Burst",
        "G-Max Gold Rush",
        "G-Max Gravitas",
        "G-Max Hydrosnipe",
        "G-Max Malodor",
        "G-Max Meltdown",
        "G-Max One Blow",
        "G-Max Rapid Flow",
        "G-Max Replenish",
        "G-Max Resonance",
        "G-Max Sandblast",
        "G-Max Smite",
        "G-Max Snooze",
        "G-Max Steelsurge",
        "G-Max Stonesurge",
        "G-Max Stun Shock",
        "G-Max Sweetness",
        "G-Max Tartness",
        "G-Max Terror",
        "G-Max Vine Lash",
        "G-Max Volcalith",
        "G-Max Volt Crash",
        "G-Max Wildfire",
        "G-Max Wind Rage",
        "Gastro Acid",
        "Gear Grind",
        "Gear Up",
        "Genesis Supernova",
        "Geomancy",
        "Giga Drain",
        "Giga Impact",
        "Gigaton Hammer",
        "Gigavolt Havoc",
        "Glacial Lance",
        "Glaciate",
        "Glaive Rush",
        "Glare",
        "Glitzy Glow",
        "Grass Knot",
        "Grass Pledge",
        "Grass Whistle",
        "Grassy Glide",
        "Grassy Terrain",
        "Grav Apple",
        "Gravity",
        "Growl",
        "Growth",
        "Grudge",
        "Guard Split",
        "Guard Swap",
        "Guardian of Alola",
        "Guillotine",
        "Gunk Shot",
        "Gust",
        "Gyro Ball",
        "Hail",
        "Hammer Arm",
        "Happy Hour",
        "Hard Press",
        "Harden",
        "Haze",
        "Head Charge",
        "Head Smash",
        "Headbutt",
        "Headlong Rush",
        "Heal Bell",
        "Heal Block",
        "Heal Order",
        "Heal Pulse",
        "Healing Wish",
        "Heart Stamp",
        "Heart Swap",
        "Heat Crash",
        "Heat Wave",
        "Heavy Slam",
        "Helping Hand",
        "Hex",
        "Hidden Power",
        "High Horsepower",
        "High Jump Kick",
        "Hold Back",
        "Hold Hands",
        "Hone Claws",
        "Horn Attack",
        "Horn Drill",
        "Horn Leech",
        "Howl",
        "Hurricane",
        "Hydro Cannon",
        "Hydro Pump",
        "Hydro Steam",
        "Hydro Vortex",
        "Hyper Beam",
        "Hyper Drill",
        "Hyper Fang",
        "Hyper Voice",
        "Hyperspace Fury",
        "Hyperspace Hole",
        "Hypnosis",
        "Ice Ball",
        "Ice Beam",
        "Ice Burn",
        "Ice Fang",
        "Ice Hammer",
        "Ice Punch",
        "Ice Shard",
        "Ice Spinner",
        "Icicle Crash",
        "Icicle Spear",
        "Icy Wind",
        "Imprison",
        "Incinerate",
        "Infernal Parade",
        "Inferno",
        "Inferno Overdrive",
        "Infestation",
        "Ingrain",
        "Instruct",
        "Ion Deluge",
        "Iron Defense",
        "Iron Head",
        "Iron Tail",
        "Ivy Cudgel",
        "Jaw Lock",
        "Jet Punch",
        "Judgment",
        "Jump Kick",
        "Jungle Healing",
        "Karate Chop",
        "Kinesis",
        "King's Shield",
        "Knock Off",
        "Kowtow Cleave",
        "Land's Wrath",
        "Laser Focus",
        "Lash Out",
        "Last Resort",
        "Last Respects",
        "Lava Plume",
        "Leaf Blade",
        "Leaf Storm",
        "Leaf Tornado",
        "Leafage",
        "Leech Life",
        "Leech Seed",
        "Leer",
        "Let's Snuggle Forever",
        "Lick",
        "Life Dew",
        "Light of Ruin",
        "Light Screen",
        "Light That Burns the Sky",
        "Liquidation",
        "Lock-On",
        "Lovely Kiss",
        "Low Kick",
        "Low Sweep",
        "Lucky Chant",
        "Lumina Crash",
        "Lunar Blessing",
        "Lunar Dance",
        "Lunge",
        "Luster Purge",
        "Mach Punch",
        "Magic Coat",
        "Magic Powder",
        "Magic Room",
        "Magical Leaf",
        "Magical Torque",
        "Magma Storm",
        "Magnet Bomb",
        "Magnet Rise",
        "Magnetic Flux",
        "Magnitude",
        "Make It Rain",
        "Malicious Moonsault",
        "Malignant Chain",
        "Mat Block",
        "Matcha Gotcha",
        "Max Airstream",
        "Max Darkness",
        "Max Flare",
        "Max Flutterby",
        "Max Geyser",
        "Max Guard",
        "Max Hailstorm",
        "Max Knuckle",
        "Max Lightning",
        "Max Mindstorm",
        "Max Ooze",
        "Max Overgrowth",
        "Max Phantasm",
        "Max Quake",
        "Max Rockfall",
        "Max Starfall",
        "Max Steelspike",
        "Max Strike",
        "Max Wyrmwind",
        "Me First",
        "Mean Look",
        "Meditate",
        "Mega Drain",
        "Mega Kick",
        "Mega Punch",
        "Megahorn",
        "Memento",
        "Menacing Moonraze Maelstrom",
        "Metal Burst",
        "Metal Claw",
        "Metal Sound",
        "Meteor Assault",
        "Meteor Beam",
        "Meteor Mash",
        "Metronome",
        "Mighty Cleave",
        "Milk Drink",
        "Mimic",
        "Mind Blown",
        "Mind Reader",
        "Minimize",
        "Miracle Eye",
        "Mirror Coat",
        "Mirror Move",
        "Mirror Shot",
        "Mist",
        "Mist Ball",
        "Misty Explosion",
        "Misty Terrain",
        "Moonblast",
        "Moongeist Beam",
        "Moonlight",
        "Morning Sun",
        "Mortal Spin",
        "Mountain Gale",
        "Mud Bomb",
        "Mud Shot",
        "Mud Sport",
        "Mud-Slap",
        "Muddy Water",
        "Multi-Attack",
        "Mystical Fire",
        "Mystical Power",
        "Nasty Plot",
        "Natural Gift",
        "Nature Power",
        "Nature's Madness",
        "Needle Arm",
        "Never-Ending Nightmare",
        "Night Daze",
        "Night Shade",
        "Night Slash",
        "Nightmare",
        "No Retreat",
        "Noble Roar",
        "Noxious Torque",
        "Nuzzle",
        "Oblivion Wing",
        "Obstruct",
        "Oceanic Operetta",
        "Octazooka",
        "Octolock",
        "Odor Sleuth",
        "Ominous Wind",
        "Order Up",
        "Origin Pulse",
        "Outrage",
        "Overdrive",
        "Overheat",
        "Pain Split",
        "Parabolic Charge",
        "Parting Shot",
        "Pay Day",
        "Payback",
        "Peck",
        "Perish Song",
        "Petal Blizzard",
        "Petal Dance",
        "Phantom Force",
        "Photon Geyser",
        "Pika Papow",
        "Pin Missile",
        "Plasma Fists",
        "Play Nice",
        "Play Rough",
        "Pluck",
        "Poison Fang",
        "Poison Gas",
        "Poison Jab",
        "Poison Powder",
        "Poison Sting",
        "Poison Tail",
        "Pollen Puff",
        "Poltergeist",
        "Population Bomb",
        "Pounce",
        "Pound",
        "Powder",
        "Powder Snow",
        "Power Gem",
        "Power Shift",
        "Power Split",
        "Power Swap",
        "Power Trick",
        "Power Trip",
        "Power Whip",
        "Power-Up Punch",
        "Precipice Blades",
        "Present",
        "Prismatic Laser",
        "Protect",
        "Psybeam",
        "Psyblade",
        "Psych Up",
        "Psychic",
        "Psychic Fangs",
        "Psychic Noise",
        "Psychic Terrain",
        "Psycho Boost",
        "Psycho Cut",
        "Psycho Shift",
        "Psyshield Bash",
        "Psyshock",
        "Psystrike",
        "Psywave",
        "Pulverizing Pancake",
        "Punishment",
        "Purify",
        "Pursuit",
        "Pyro Ball",
        "Quash",
        "Quick Attack",
        "Quick Guard",
        "Quiver Dance",
        "Rage",
        "Rage Fist",
        "Rage Powder",
        "Raging Bull",
        "Raging Fury",
        "Rain Dance",
        "Rapid Spin",
        "Razor Leaf",
        "Razor Shell",
        "Razor Wind",
        "Recover",
        "Recycle",
        "Reflect",
        "Reflect Type",
        "Refresh",
        "Relic Song",
        "Rest",
        "Retaliate",
        "Return",
        "Revelation Dance",
        "Revenge",
        "Reversal",
        "Revival Blessing",
        "Rising Voltage",
        "Roar",
        "Roar of Time",
        "Rock Blast",
        "Rock Climb",
        "Rock Polish",
        "Rock Slide",
        "Rock Smash",
        "Rock Throw",
        "Rock Tomb",
        "Rock Wrecker",
        "Role Play",
        "Rolling Kick",
        "Rollout",
        "Roost",
        "Rototiller",
        "Round",
        "Ruination",
        "Sacred Fire",
        "Sacred Sword",
        "Safeguard",
        "Salt Cure",
        "Sand Attack",
        "Sand Tomb",
        "Sandsear Storm",
        "Sandstorm",
        "Sappy Seed",
        "Savage Spin-Out",
        "Scald",
        "Scale Shot",
        "Scary Face",
        "Scorching Sands",
        "Scratch",
        "Screech",
        "Searing Shot",
        "Searing Sunraze Smash",
        "Secret Power",
        "Secret Sword",
        "Seed Bomb",
        "Seed Flare",
        "Seismic Toss",
        "Self-Destruct",
        "Shadow Ball",
        "Shadow Bone",
        "Shadow Claw",
        "Shadow Force",
        "Shadow Punch",
        "Shadow Sneak",
        "Sharpen",
        "Shattered Psyche",
        "Shed Tail",
        "Sheer Cold",
        "Shell Side Arm",
        "Shell Smash",
        "Shell Trap",
        "Shelter",
        "Shift Gear",
        "Shock Wave",
        "Shore Up",
        "Signal Beam",
        "Silk Trap",
        "Silver Wind",
        "Simple Beam",
        "Sing",
        "Sinister Arrow Raid",
        "Sizzly Slide",
        "Sketch",
        "Skill Swap",
        "Skitter Smack",
        "Skull Bash",
        "Sky Attack",
        "Sky Drop",
        "Sky Uppercut",
        "Slack Off",
        "Slam",
        "Slash",
        "Sleep Powder",
        "Sleep Talk",
        "Sludge",
        "Sludge Bomb",
        "Sludge Wave",
        "Smack Down",
        "Smart Strike",
        "Smelling Salts",
        "Smog",
        "Smokescreen",
        "Snap Trap",
        "Snarl",
        "Snatch",
        "Snipe Shot",
        "Snore",
        "Snowscape",
        "Soak",
        "Soft-Boiled",
        "Solar Beam",
        "Solar Blade",
        "Sonic Boom",
        "Soul-Stealing 7-Star Strike",
        "Spacial Rend",
        "Spark",
        "Sparkling Aria",
        "Sparkly Swirl",
        "Spectral Thief",
        "Speed Swap",
        "Spicy Extract",
        "Spider Web",
        "Spike Cannon",
        "Spikes",
        "Spiky Shield",
        "Spin Out",
        "Spirit Break",
        "Spirit Shackle",
        "Spit Up",
        "Spite",
        "Splash",
        "Splintered Stormshards",
        "Splishy Splash",
        "Spore",
        "Spotlight",
        "Springtide Storm",
        "Stealth Rock",
        "Steam Eruption",
        "Steamroller",
        "Steel Beam",
        "Steel Roller",
        "Steel Wing",
        "Sticky Web",
        "Stockpile",
        "Stoked Sparksurfer",
        "Stomp",
        "Stomping Tantrum",
        "Stone Axe",
        "Stone Edge",
        "Stored Power",
        "Storm Throw",
        "Strange Steam",
        "Strength",
        "Strength Sap",
        "String Shot",
        "Struggle",
        "Struggle Bug",
        "Stuff Cheeks",
        "Stun Spore",
        "Submission",
        "Substitute",
        "Subzero Slammer",
        "Sucker Punch",
        "Sunny Day",
        "Sunsteel Strike",
        "Super Fang",
        "Supercell Slam",
        "Superpower",
        "Supersonic",
        "Supersonic Skystrike",
        "Surf",
        "Surging Strikes",
        "Swagger",
        "Swallow",
        "Sweet Kiss",
        "Sweet Scent",
        "Swift",
        "Switcheroo",
        "Swords Dance",
        "Synchronoise",
        "Synthesis",
        "Syrup Bomb",
        "Tachyon Cutter",
        "Tackle",
        "Tail Glow",
        "Tail Slap",
        "Tail Whip",
        "Tailwind",
        "Take Down",
        "Take Heart",
        "Tar Shot",
        "Taunt",
        "Tearful Look",
        "Teatime",
        "Techno Blast",
        "Tectonic Rage",
        "Teeter Dance",
        "Telekinesis",
        "Teleport",
        "Temper Flare",
        "Tera Blast",
        "Tera Starstorm",
        "Terrain Pulse",
        "Thief",
        "Thousand Arrows",
        "Thousand Waves",
        "Thrash",
        "Throat Chop",
        "Thunder",
        "Thunder Cage",
        "Thunder Fang",
        "Thunder Punch",
        "Thunder Shock",
        "Thunder Wave",
        "Thunderbolt",
        "Thunderclap",
        "Thunderous Kick",
        "Tickle",
        "Tidy Up",
        "Topsy-Turvy",
        "Torch Song",
        "Torment",
        "Toxic",
        "Toxic Spikes",
        "Toxic Thread",
        "Trailblaze",
        "Transform",
        "Tri Attack",
        "Trick",
        "Trick Room",
        "Trick-or-Treat",
        "Triple Arrows",
        "Triple Axel",
        "Triple Dive",
        "Triple Kick",
        "Trop Kick",
        "Trump Card",
        "Twin Beam",
        "Twineedle",
        "Twinkle Tackle",
        "Twister",
        "U-turn",
        "Upper Hand",
        "Uproar",
        "V-create",
        "Vacuum Wave",
        "Veevee Volley",
        "Venom Drench",
        "Venoshock",
        "Victory Dance",
        "Vine Whip",
        "Vise Grip",
        "Vital Throw",
        "Volt Switch",
        "Volt Tackle",
        "Wake-Up Slap",
        "Water Gun",
        "Water Pledge",
        "Water Pulse",
        "Water Shuriken",
        "Water Sport",
        "Water Spout",
        "Waterfall",
        "Wave Crash",
        "Weather Ball",
        "Whirlpool",
        "Whirlwind",
        "Wicked Blow",
        "Wicked Torque",
        "Wide Guard",
        "Wild Charge",
        "Wildbolt Storm",
        "Will-O-Wisp",
        "Wing Attack",
        "Wish",
        "Withdraw",
        "Wonder Room",
        "Wood Hammer",
        "Work Up",
        "Worry Seed",
        "Wrap",
        "Wring Out",
        "X-Scissor",
        "Yawn",
        "Zap Cannon",
        "Zen Headbutt",
        "Zing Zap",
        "Zippy Zap",
};

private:
         // TODO


};

#endif // SHAREDWINDOWINFO_H
